### ISSUE TITLE
what is  RELAY_API_URL‘s  value?

### ISSUE THREAD

**Issue by LevenWin** [LIT-Protocol/oauth-pkp-signup-example#3]
Please help!

`const  RELAY_API_URL = process.env.RELAY_API_URL || 'http://localhost:3000';`

error: 
![image](https://user-images.githubusercontent.com/16890393/206216961-38377f0d-3e69-4e25-9840-995a40e3ca21.png)

![image](https://user-images.githubusercontent.com/16890393/206216838-8a8402f5-1807-499c-bdf8-13d254f46ceb.png)

**Comment by johnnynanjiang** [comment]
@hwrdtm can you please help? Thanks.

**Comment by hwrdtm** [comment]
https://relay-server-staging.herokuapp.com

Try putting the following in a `.env` locally:


```
REACT_APP_RELAY_API_URL=https://relay-server-staging.herokuapp.com
```

**Comment by johnnynanjiang** [comment]
> https://relay-server-staging.herokuapp.com
> 
> Try putting the following in a `.env` locally:
> 
> ```
> REACT_APP_RELAY_API_URL=https://relay-server-staging.herokuapp.com
> ```

Thanks @hwrdtm cc @LevenWin 

We have set up a relay server locally using the repo https://github.com/LIT-Protocol/relay-server

For others benefit, `.env` file looks like this

```
REDIS_URL=redis://localhost:6379
PORT=3001
LIT_TXSENDER_RPC_URL=https://rpc.ankr.com/polygon_mumbai
LIT_TXSENDER_PRIVATE_KEY={your private key}
GOOGLE_CLIENT_ID={your google client id}
```

**Comment by acrylicfiddle** [comment]
> https://relay-server-staging.herokuapp.com
> 
> Try putting the following in a `.env` locally:
> 
> ```
> REACT_APP_RELAY_API_URL=https://relay-server-staging.herokuapp.com
> ```

I used this and it says I dont have an API key. can you help me with this? @hwrdtm

**Comment by hwrdtm** [comment]
Please follow the instructions to apply for an API key here https://forms.gle/osJfmRR2PuZ46Xf98 and we will get in touch with an API key for you to use shortly.

**Comment by acrylicfiddle** [comment]
@hwrdtm it says its not accessible
![image](https://user-images.githubusercontent.com/24580317/209600180-4a9f91eb-0463-4dd7-90dd-94fa06719d5e.png)

**Comment by acrylicfiddle** [comment]
@hwrdtm I am running into an issue which says no unminted routed tokens. do you know who can call the router contract and add new tokens?

also why is this done in this way? why cant it mint a new token with the sub:aud token id, if it exists then it can just revert?

error:
`There are no unminted routed token ids to mint`

**Comment by hwrdtm** [comment]
> @hwrdtm it says its not accessible ![image](https://user-images.githubusercontent.com/24580317/209600180-4a9f91eb-0463-4dd7-90dd-94fa06719d5e.png)

Try now

**Comment by hwrdtm** [comment]
> @hwrdtm I am running into an issue which says no unminted routed tokens. do you know who can call the router contract and add new tokens?
> 
> also why is this done in this way? why cant it mint a new token with the sub:aud token id, if it exists then it can just revert?
> 
> error: `There are no unminted routed token ids to mint`

Can you please share more details about the error you're facing and the steps you took? Please share details around any transactions you sent, and API calls that are failing.

**Comment by acrylicfiddle** [comment]
@hwrdtm perfect thanks, filled it out now.

The error I am seeing is from the relay-server. I ran it locally and was able to successfully connect to Redis /google etc. But when the mintPKP function is called it reverts with - `There are no unminted routed token ids to mint`
Just logging in with google oauth and trying to connect on boilerplate code. Was talking to Brendan and he said he minted some more keys, but it's still failing for me.

exact error from relay server code:
` reason: 'execution reverted: There are no unminted routed token ids to mint',
      code: 'UNPREDICTABLE_GAS_LIMIT',
      method: 'estimateGas',`

**Comment by GTC6244** [comment]
@acrylicfiddle  - I'm closing this off, per our conversation yesterday when you indicated a successful mint.   The root of the issue was 10x increase in interest in PKPs on the mumbai testnet.   We're implementing some new procedures to help with demand in the next few days.
